---
version: '3.3'
services:
  web:
    build: .
    ports:
      - 8666:8000
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/walkie
      - NODE_ENV=production
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.2
    ports:
      - 27666:27017
